In [1]:
import numpy as np

In [2]:
arr = np.array([[[4,3,6]],[[6,8,4]],[[8,10,12]],[[12,16,18]]])

In [3]:
np.ndim(arr)

3

In [4]:
np.sort(arr)

array([[[ 3,  4,  6]],

       [[ 4,  6,  8]],

       [[ 8, 10, 12]],

       [[12, 16, 18]]])

In [5]:
np.where(arr==4)

(array([0, 1], dtype=int64),
 array([0, 0], dtype=int64),
 array([0, 2], dtype=int64))

In [6]:
np.where(arr==[12,16,18])

(array([3, 3, 3], dtype=int64),
 array([0, 0, 0], dtype=int64),
 array([0, 1, 2], dtype=int64))